### ISSUE TITLE
Drop down menus run off screen when zoomed in or on low res settings

### ISSUE THREAD

**Issue by FuzzyBearBTC** [super3/peercoin.net#215]
http://i.imgur.com/dXF3xsR.png as reported in this post here http://www.peercointalk.org/index.php?topic=3382.0

I recreated by zooming in on the page, only one zoom in seems to have an issue just needs the ddl to be bumped to the right but might not be possible

**Comment by TheWildHorse** [comment]
Fixed in 3396ac4a164b3830b3bace04c62819015568069f.
