### ISSUE TITLE
Updating developers page

### ISSUE THREAD

**Issue by ghost** [super3/peercoin.net#226]
http://peercoin.net/developers is now out of date as it says that v0.5 will include cold minting and optional checkpointing. This has now been pushed back to v0.6, with v0.5 scheduled to add support for peermessage and security protocol adjustments instead (https://www.peercointalk.org/index.php?topic=4074.0).

To avoid having to update the page frequently, maybe the first sentence under the "Core Protocol" heading could be changed.﻿ Suggestion for new text:

"A future edition of the core protocol wallet will contain the following features:"

The two paragraphs below this may also need to be updated, as they both say the feature will be added in the "next version". I also suggest adding a link to sigmike's proposal thread (https://www.peercointalk.org/index.php?topic=2783.0) in the cold wallet minting paragraph.

Other possible changes for this page would be to add ppcsuite (https://github.com/ppcsuite) and peerapps (https://www.peercointalk.org/index.php?board=72.0) under "﻿Current community projects", though these projects do not have logos like the other projects listed there.

**Comment by ritvikgautam** [comment]
Created a pull request #235

**Comment by MAL315** [comment]
I merged the developer changes. I'm not familiar with PPCSuite but it hasn't been updated in a while, is it still active? The PeerApps link is dead, do you have an updated one? If they don't need to be added anymore I'll just close the issue.

Thanks

**Comment by MAL315** [comment]
Please re-open if you would like to discuss.
