### ISSUE TITLE
Add PPC Pool

### ISSUE THREAD

**Issue by AsicTrade** [super3/peercoin.net#243]
Новый, русский пулл Peercoin
https://PPC.AsicTrade.com/index.php
PROP 1%fee. DDOS+ssl(https)+ stratum
NOMP+MPOS
5 port fixDiff
1 port varDiff
10/10

**Comment by MAL315** [comment]
The link or pool doesn't seem to be active anymore if you could please confirm. Otherwise I'll close the issue.

Thanks

**Comment by AsicTrade** [comment]
Hi, yes closeс Ув. команда AsicTrade Официальный сайт - https://AsicTrade.com-------------------------AsicTrade.com - Криптографическое оборудованиеот лучших производителей мира.4:52, 19 сентября 2016 г., MAL315 <notifications@github.com>:The link or pool doesn't seem to be active anymore if you could please confirm. Otherwise I'll close the issue. Thanks —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
