### ISSUE TITLE
Invalid HTTPS certificate for peercoin.net as of Sep 14 2016

### ISSUE THREAD

**Issue by hoschiCZ** [super3/peercoin.net#268]
On Firefox stable on Windows. FF says it is not trusted because issuer: 
`CN = COMODO RSA Domain Validation Secure Server CA
O = COMODO CA Limited
L = Salford
ST = Greater Manchester
C = GB
` is unknown.

**Comment by hoschiCZ** [comment]
Works on Microsoft Edge btw.

**Comment by MAL315** [comment]
I'm running Firefox ESR 45.3.0 on Debian and it works fine on mine (says Secure Connection with green padlock).

**Comment by MAL315** [comment]
Is it still an issue on your version of Firefox?

**Comment by hoschiCZ** [comment]
Yes, it is. FF version 49 on Windows 10.

**Comment by MAL315** [comment]
@super3 Might need your help for this one.
https://support.comodo.com/?/Knowledgebase/Article/View/683
https://support.mozilla.org/en-US/questions/1042797

**Comment by D9ping** [comment]
The current peercoin.net certificate issued by comodo is expired. (as of 1 november 2016)

**Comment by MAL315** [comment]
Yea, super3 bought a new one but just has to put it in. Hopefully it'll fix the firefox issue at the same time.

**Comment by TheWildHorse** [comment]
New certificate has been installed and the certificate authority issue fixed.

**Comment by MAL315** [comment]
I think we can close this. If the issue isn't resolved on Firefox please open up a new issue and we can investigate. A new certificate was purchased recently so I see no reason for it not to work.
