### ISSUE TITLE
Transifex Translation isn't working

### ISSUE THREAD

**Issue by MAL315** [super3/peercoin.net#276]
Changes on the English pages aren't showing up on https://www.transifex.com/peercoinnet/website-ppc/. It stills says 0 strings to translate even though changes were made on the main pages and under translation_source.

**Comment by MAL315** [comment]
Another possible alternative, it's being used for peerunity - https://www.getlocalization.com

**Comment by MAL315** [comment]
If we can get access from @TheWildHorse to the original Transifex page I'll be able to fix the links otherwise this will probably wait until the full website redesign.

**Comment by super3** [comment]
@MAL315 Asking @TheWildHorse If he can add you.

**Comment by super3** [comment]
@MAL315 Said he added you.

**Comment by MAL315** [comment]
I deleted all my Transifex accounts since he wasn't responding so I'm not sure which account he added but I don't have access to it anymore.. I created a new one with username MAL_. Not sure if you could ask him again.

**Comment by MAL315** [comment]
Seems I have access now. I'll take another look.
