### ISSUE TITLE
Website repository should be moved to Peercoin organization repo.

### ISSUE THREAD

**Issue by peerchemist** [super3/peercoin.net#313]
https://github.com/super3/peercoin.net to https://github.com/peercoin/peercoin.net

**Comment by MAL315** [comment]
Who owns /peercoin? Since it's super3's repository I'd probably want his ok before we move it as he still pays for the server itself.

**Comment by peerchemist** [comment]
SunnyKing is the owner of /peercoin

**Comment by MAL315** [comment]
Is he the only one who can give access on github? I'm not sure who would 
need access (super3) could confirm based on his current permissions.

I only see hrobeers and you under people (sunnyking isn't listed) - 
https://github.com/peercoin

**Comment by MAL315** [comment]
@super3 any issues with moving the super3/peercoin.net repository to github.com/peercoin?

**Comment by MAL315** [comment]
Move has taken place. New repo can be found under the peercoin group (https://github.com/peercoin) or more specifically for peercoin.net at https://github.com/peercoin/peercoin.net.
