### ISSUE TITLE
github page  peercoin.net backlink not using https

### ISSUE THREAD

**Issue by D9ping** [super3/peercoin.net#314]
The website back link on super3/peercoin.net github page is still using insecure http and that causes a additional redirect to use http**s**. Change the link to https://peercoin.net.
The same goes for the github.com/peercoin github organisation page (maintained by @hrobeers and @peerchemist)

**Comment by MAL315** [comment]
The link used in the github "description"? For example "Web files for Peercoin.net http://peercoin.net" when accessing github.com/super3/peercoin.net? I think only @super3 can change it.

For github.com/peercoin under "Secure and sustainable peer-to-peer cryptocurrency." I guess @hrobeers or @peerchemist. I'm not 100% certain who owns it.

**Comment by peerchemist** [comment]
> I guess @hrobeers or @peerchemist. I'm not 100% certain who owns it.

SK owns it, me and @hrobeers have full access though.

**Comment by D9ping** [comment]
yeah, the github description.

**Comment by MAL315** [comment]
Now that the repo has moved to https://github.com/peercoin/peercoin.net I've updated the https link for the peercoin.net repo. Peerchemist will have to change the link on the main group at https://github.com/peercoin though. He's in this thread but I've also sent him a message on peercoin.chat so I'll close this issue.
